server:
    port: 9191
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/fitinc1
        username: root
        password: superuser
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: prinstonrebello@gmail.com
        password: xijnbsvatytkjmid
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

