name: Docker Image CI for GCP

on:
    push:
        branches:
            - 'main'
        paths:
            - 'login/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v2
              with:
                path: 'login'

            - name: Install GCP CLI
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
                export_default_credentials: true
            
            - name: Set up JDK 21 for x64
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
                architecture: x64

            - name: Print Current Directory
              run: pwd
              
            - name: Print Login Directory Contents
              run: ls -la login

            - name: Build with Maven
              working-directory: 'login'
              run: mvn clean package

            - name: Build & Push Docker Image
              env:
                GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
              working-directory: 'login'
              run:
                gcloud auth configure-docker us-central1-doker.pkg.dev
                docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/wellness-tracking-service-containers/login-service:latest --file Dockerfile .
                docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/wellness-tracking-service-containers/login-service:latest
