name: Docker Image CI for GCP

on:
    push:
        branches:
            - 'main'
        paths:
            - 'login/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v2
              with:
                path: 'login'

            - name: Install GCP CLI
              uses: google-github-actions/setup-gcloud@master
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
                export_default_credentials: true

            - name: Build Docker Image
              working-directory: 'login'
              run: docker build -t login-service:latest
              
            - name: Configure Docker Client
              run: |-
                gcloud auth configure-docker --quite

            - name: Push Docker Image
              env:
                GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
              run:
                docker push gcr.io/$GCP_PROJECT_ID/wellness-tracking-service-containers/login-service:latest
